### PR TITLE
Added Chinese Names

### PR DESCRIPTION
**Pull request by csrutil**
Added Chinese Names.

### CODE REVIEW

**Comment by marocchino** [comment]
Hello, @csrutil! This is your first Pull Request that will be reviewed by [Ebert](https://ebertapp.io/), an automatic Code Review service. It will leave comments on this diff with potential issues and style violations found in the code as you push new commits. You can also see all the issues found on this Pull Request on its [review page](https://ebertapp.io/github/marocchino/ffaker/pulls/3). Please check our [documentation](https://docs.ebertapp.io) for more information.

**Comment by marocchino** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 2 fixed issues! 🎉

You can see more details about this review at https://ebertapp.io/github/marocchino/ffaker/pulls/3.

**Comment by marocchino** [comment]
thanks. :)

**Comment by csrutil** [comment]
It's my pleasure. : )

**Pull request merged**
